In [1]:
# Import Numpy Library
import numpy as np

In [2]:
# Create array with np.array()
mylist = [1,2,3]

x = np.array(mylist)
x

array([1, 2, 3])

In [3]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [4]:
m = np.array([[7,8,9], [10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [5]:
# Show the array size with .shape
y.shape

(3,)

In [6]:
# Create Numpy range array with np.arange()
n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [7]:
# Reshape the array with reshape()
# reshape will not change the original data array
n = n.reshape(3,5)
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [8]:
# Create array with split up interval with np.linspace()
o = np.linspace(0, 4, 9)

# Resize the array with resize()
# resize() will change the original data array
# https://www.coursera.org/learn/python-data-analysis/discussions/weeks/1/threads/ndte2LTWEeeKBBKJgknU5g
o = o.resize(3,3)
o

In [9]:
# Create array full of 1
# But it will be in float
np.ones(3)

array([1., 1., 1.])

In [10]:
# Create array full of 0
# But it will be in float
np.zeros(3)

array([0., 0., 0.])

In [11]:
# Fill diagonal with 1, others will be 0
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Fill diagonal with list
np.diag(x)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [13]:
np.array([1,2,3]) * 3

array([3, 6, 9])

In [14]:
np.repeat([1,2,3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [15]:
p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
# Stack two array together in vertical align
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [17]:
# Stack two array together in horizontal align
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operation

In [18]:
x + y

array([5, 7, 9])

In [19]:
x * y

array([ 4, 10, 18])

In [20]:
x**2

array([1, 4, 9], dtype=int32)

In [21]:
x.dot(y)

32

In [22]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [23]:
z.shape

(2, 3)

In [24]:
# Transpose z array
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [25]:
z.T.shape

(3, 2)

In [26]:
# See the value data type
z.dtype

dtype('int32')

In [27]:
# Cast to new data type with .astype()
z = z.astype('f')
z.dtype

dtype('float32')

# Column operations

In [28]:
a = np.array([-4, -2, 1, 3, 5])
a

array([-4, -2,  1,  3,  5])

In [29]:
a.sum()

3

In [30]:
a.max()

5

In [31]:
a.min()

-4

In [32]:
a.mean()

0.6

In [33]:
# Find standard deviation
a.std()

3.2619012860600183

In [34]:
# Find index of maximum value
a.argmax()

4

In [35]:
a.argmin()

0

# Indexing and Slicing

In [36]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [37]:
s[0]

0

In [38]:
s[0:3]

array([0, 1, 4], dtype=int32)

In [39]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

## with 2 dimension array

In [40]:
r = np.arange(36)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [41]:
# Get value of row 2 and colunn 2
r[2,2]
['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]

In [42]:
r[3, 3:6]

array([21, 22, 23])

In [43]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [44]:
r[-1,::2]

array([30, 32, 34])

In [45]:
# You can use conditional to find array
r[r > 30]

array([31, 32, 33, 34, 35])

In [46]:
# Set the value from a condition
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [47]:
# Things to avoid when copying the numpy array

r2 = r[:3,:3]
r2[:] = 0
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [48]:
# To fix this issue, use copy()
r_cpy = r.copy()
r_cpy[:] = 10

print(r_cpy,end='\n\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


# Iterating Over Array

In [49]:
test = np.random.randint(0, 10, (4, 3))
test

array([[5, 4, 9],
       [2, 7, 7],
       [1, 7, 4],
       [5, 4, 8]])

In [50]:
for row in test:
    print(row)

[5 4 9]
[2 7 7]
[1 7 4]
[5 4 8]


In [51]:
for i in range(len(test)):
    print(test[i])

[5 4 9]
[2 7 7]
[1 7 4]
[5 4 8]


In [52]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [5 4 9]
row 1 is [2 7 7]
row 2 is [1 7 4]
row 3 is [5 4 8]


In [53]:
test2 = test**2

for i,j in zip(test, test2):
    print('{} + {} = {}'.format(i, j, i+j))

[5 4 9] + [25 16 81] = [30 20 90]
[2 7 7] + [ 4 49 49] = [ 6 56 56]
[1 7 4] + [ 1 49 16] = [ 2 56 20]
[5 4 8] + [25 16 64] = [30 20 72]
