# Introduction to Numpy
## Import of Numpy
Import it with `import`. 

Don't forget to install the module first with `!pip3 install numpy`
(`!` in front of pip is required)

In [1]:
# Import Numpy Library
!pip3 install numpy

# and import the numpy and named it as np
import numpy as np

## Create Numpy Array
Create an array with `np.array()`

In [6]:
mylist = [1,2,3]

# Create an array from a list
x = np.array(mylist)
print(x)

print()

y = np.array([[1,2,3], [2,3,4]])
print(y)

[1 2 3]

[[1 2 3]
 [2 3 4]
 [2 1 0]]


## Arranging the array
- Show the array shape with `.shape`
- Create a array range with `np.arange()`
- Reshaping (not changing the object shape) with `.reshape()`
- Create an array range (with same difference) with `np.linspace()`

In [7]:
y.shape

(3, 3)

In [10]:
n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [4]:
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [5]:
o = np.linspace(0, 4, 9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

## Create array with ones and zeros
- Create array of ones with `np.ones()`
- Create array of zeros with `np.zeros()`
- Create array (in which ones are in diagonal and others are zeros) with `np.eye()`
- Create diagonal from other array with `np.diag()`

In [6]:
np.ones(3)

array([1., 1., 1.])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
# Fill diagonal with 1
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# Fill diagonal with list
print(x)
np.diag(x)

[1 2 3]


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])