In [1]:
# Import Numpy Library
import numpy as np

In [3]:
mylist = [1,2,3]

x = np.array(mylist)
x

array([1, 2, 3])

In [12]:
# Create array with np.array()
y = np.array([[1,2,3], [2,3,4]])
y

array([[1, 2, 3],
       [2, 3, 4]])

In [14]:
# Show the array size with .shape
y.shape

(2, 3)

In [17]:
# Create Numpy range array with np.arange()
n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [19]:
# Reshape the array with reshape()
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [23]:
# Create array with split up interval with np.linspace()
o = np.linspace(0, 4, 9)

o = o.reshape(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [25]:
np.ones(3)

array([0., 0., 0.])

In [26]:
np.zeros(3)

array([0., 0., 0.])

In [32]:
# Fill diagonal with 1
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
# Fill diagonal with list
np.diag(x)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])